name: pds1920
channels:
  - conda-forge
  - defaults
dependencies:
  - appnope=0.1.0=py37_1000
  - attrs=19.3.0=py_0
  - backcall=0.1.0=py_0
  - blas=1.0=mkl
  - bleach=3.1.0=py_0
  - bzip2=1.0.8=h01d97ff_1
  - ca-certificates=2019.9.11=hecc5488_0
  - certifi=2019.9.11=py37_0
  - cycler=0.10.0=py_1
  - dbus=1.13.6=h2f22bb5_0
  - decorator=4.4.0=py_0
  - defusedxml=0.6.0=py_0
  - entrypoints=0.3=py37_1000
  - expat=2.2.5=h4a8c4bd_1004
  - freetype=2.10.0=h24853df_1
  - gettext=0.19.8.1=h46ab8bc_1002
  - glib=2.58.3=h9d45998_1002
  - icu=64.2=h6de7cb9_1
  - importlib_metadata=0.23=py37_0
  - intel-openmp=2019.4=233
  - ipykernel=5.1.3=py37h5ca1d4c_0
  - ipython=7.8.0=py37h5ca1d4c_0
  - ipython_genutils=0.2.0=py_1
  - ipywidgets=7.5.1=py_0
  - jedi=0.15.1=py37_0
  - jinja2=2.10.3=py_0
  - jpeg=9c=h1de35cc_1001
  - jsonschema=3.1.1=py37_0
  - jupyter=1.0.0=py_2
  - jupyter_client=5.3.3=py37_1
  - jupyter_console=6.0.0=py_0
  - jupyter_contrib_core=0.3.3=py_2
  - jupyter_core=4.5.0=py_0
  - jupyter_nbextensions_configurator=0.4.1=py37_0
  - kiwisolver=1.1.0=py37h770b8ee_0
  - libblas=3.8.0=14_mkl
  - libcblas=3.8.0=14_mkl
  - libclang=8.0.1=h770b8ee_1
  - libcxx=9.0.0=h89e68fa_1
  - libffi=3.2.1=h6de7cb9_1006
  - libgfortran=3.0.1=h93005f0_2
  - libiconv=1.15=h01d97ff_1005
  - liblapack=3.8.0=14_mkl
  - libllvm8=8.0.1=h770b8ee_0
  - libpng=1.6.37=h2573ce8_0
  - libsodium=1.0.17=h01d97ff_0
  - markupsafe=1.1.1=py37h1de35cc_0
  - matplotlib=3.1.1=py37_1
  - matplotlib-base=3.1.1=py37h3a684a6_1
  - mistune=0.8.4=py37h1de35cc_1000
  - mkl=2019.4=233
  - mkl-service=2.3.0=py37hfbe908c_0
  - mkl_fft=1.0.14=py37h5e564d8_0
  - mkl_random=1.1.0=py37ha771720_0
  - more-itertools=7.2.0=py_0
  - nbconvert=5.6.0=py37_1
  - nbformat=4.4.0=py_1
  - ncurses=6.1=h0a44026_1002
  - notebook=6.0.1=py37_0
  - nspr=4.20=h0a44026_1000
  - nss=3.47=hcec2283_0
  - numpy=1.17.2=py37h99e6662_0
  - numpy-base=1.17.2=py37h6575580_0
  - openssl=1.1.1c=h01d97ff_0
  - pandas=0.25.1=py37h0a44026_0
  - pandoc=2.7.3=0
  - pandocfilters=1.4.2=py_1
  - parso=0.5.1=py_0
  - pcre=8.43=h4a8c4bd_0
  - pexpect=4.7.0=py37_0
  - pickleshare=0.7.5=py37_1000
  - pip=19.3.1=py37_0
  - prometheus_client=0.7.1=py_0
  - prompt_toolkit=2.0.10=py_0
  - ptyprocess=0.6.0=py_1001
  - pygments=2.4.2=py_0
  - pyparsing=2.4.2=py_0
  - pyqt=5.12.3=py37h2a560b1_0
  - pyrsistent=0.15.4=py37h01d97ff_0
  - python=3.7.3=h93065d6_1
  - python-dateutil=2.8.0=py_0
  - pytz=2019.3=py_0
  - pyyaml=5.1.2=py37h01d97ff_0
  - pyzmq=18.1.0=py37hee98d25_0
  - qt=5.12.5=h1b46049_0
  - qtconsole=4.5.5=py_0
  - readline=8.0=hcfe32e1_0
  - rise=5.5.1=py37_0
  - scipy=1.3.1=py37hab3da7d_2
  - send2trash=1.5.0=py_0
  - setuptools=41.4.0=py37_0
  - six=1.12.0=py37_1000
  - sqlite=3.30.1=h93121df_0
  - terminado=0.8.2=py37_0
  - testpath=0.4.2=py_1001
  - tk=8.6.9=h2573ce8_1003
  - tornado=6.0.3=py37h01d97ff_0
  - traitlets=4.3.3=py37_0
  - wcwidth=0.1.7=py_1
  - webencodings=0.5.1=py_1
  - wheel=0.33.6=py37_0
  - widgetsnbextension=3.5.1=py37_0
  - xz=5.2.4=h1de35cc_1001
  - yaml=0.1.7=h1de35cc_1001
  - zeromq=4.3.2=h6de7cb9_2
  - zipp=0.6.0=py_0
  - zlib=1.2.11=h0b31af3_1006
  - pip:
    - pyqt5-sip==4.19.18
    - pyqtwebengine==5.12.1
prefix: /Users/matjes/anaconda3/envs/pds1920

